list: $/rade31/simplecart/models/product/columns.yaml
modelClass: Rade31\SimpleCart\Models\Product
title: Products
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'rade31/simplecart/products/update/:id'